### ISSUE TITLE
The FAQ might contain the answers to your questions...

### ISSUE THREAD

**Issue by kristianmandrup** [Raynos/mercury#101]
Been frustrated at the lacking documentation. Apparently the docs are mostly to be found in the `/docs` folder of the source code!! And the best docs I have found so far on how to structure a real app is the `FAQ.md`. 

I found this little gem in there, showing how to define a Component. Now the only problem with this approach is that the state is local, but of course we could just as well reference global state and use some sort of Flux mechanism to mediate changes between components and global app state similar to React...

```js
function EventComponent() {
  var events = mercury.input(['toggle']);

  var state = mercury.struct({
    name: 'event name',
    isOpen: mercury.value(false),
    description: 'event description',
    events: events
  });

  events.toggle(function (data) {
    state.isOpen.set(data.value)
  })

  return { state: state }
}

EventComponent.render = function (state) {
  return h('div', [
    h('div', {
      'ev-click': mercury.event(events.eventToggle, {
        eventIndex: j,
        dayIndex: i,
        value: !event.isOpen
      })
    }, event.name),
    h('div', {
      hidden: !event.isOpen
    }, event.description)
  ])
}
```

I don't  fully understand the rendering process yet. Is there some way to tell the component which states in the global or local state object should cause a redraw of the component on change?
Feels so much more efficient than walking through the entire graph...??
How about Array Proxies or proxies in general?
If we have an iteration within the render, it should always render a new component on each iteration and that component should only re-render if its state changed relative to last time it was rendered. Is this possible currently?

How about computed properties?

```js
var Observable = require("observ")
var computed = require("observ/computed")

var one = Observable(1)
var two = Observable(2)

var together = computed([one, two], function (a, b) {
  return a + b
})

assert.equal(together(), 3)
two.set(5)
assert.equal(together(), 7)
```

But haven't seen any real app examples using this feature...

**Comment by cellvia** [comment]
i just want to say, i'd been reading and pondering virtual-dom frameworks for days now, and have been trying to wrap my head around mercury.  this thread is what finally made it click, i hope that you will or have preserved this in FAQs or something, as it may help others!!

**Comment by kristianmandrup** [comment]
Please summarise the key points on a new wiki page ;)

**Comment by Raynos** [comment]
Not a wiki page :( the wiki got corrupted / trolled. you can contribute docs in PRs on docs folder.
