### ISSUE TITLE
hg.partial on server-side

### ISSUE THREAD

**Issue by NeCkEr** [Raynos/mercury#121]
can't get hg.partial to work on server-side rendering...

any suggestions?

**Comment by Raynos** [comment]
- We use `virtual-dom-stringify` ( https://github.com/Raynos/mercury/blob/master/examples/server-rendering/server.js#L6 ) on the server.
 - The source code is here ( https://github.com/alexmingoia/virtual-dom-stringify )
 - `hg.partial` generates a thunk ( https://github.com/Raynos/vdom-thunk/blob/master/immutable-thunk.js ).
 - virtual-dom-stringify is missing an `else if (isThunk(node))` block ( https://github.com/alexmingoia/virtual-dom-stringify/blob/master/lib/stringify.js#L110 )

If you make a PR on virtual-dom-stringify to stringify thunks ( and add tests! ) then it should work.
