### ISSUE TITLE
Encapsulation

### ISSUE THREAD

**Issue by matthewp** [Raynos/mercury#129]
Hey @Raynos , one thing I'm uncertain about is how to encapsulate a component. It seems that the global state makes this difficult. The way around this seems to be to include the vdom in the component's state function and binding in there: https://github.com/Raynos/mercury/blob/master/examples/markdown/component/inlineMdEditor.js

This feels wrong to me. Can you talk me out of feeling icky about having vdom on a state object?

**Comment by Raynos** [comment]
There is a document about components here: 

 - https://github.com/Raynos/mercury/blob/master/docs/mercury-component.md

You can achieve modularity through using them as can be seen in the todomvc example.

You should not store vdom in the component's state, however putting other component's state in your own state is an excellent technique to use.

**Comment by matthewp** [comment]
Awesome, I'll read through that then. fwiw, the markdown example does put vdom into the state, so that's how I thought the pattern would be.

**Comment by matthewp** [comment]
It's still unclear to me.  If I had a `FancyInput` component how would I handle a click event without knowing about the global State? I'd want to modify just the part of state the component is aware of (the component's state), but you can't do that because you don't have access to the state atom within the render function.

**Comment by neonstalwart** [comment]
@matthewp can you point out explicitly where the vdom is in the state for the markdown example - i wrote it but i don't remember doing that (but that's not to say that i didn't).  maybe i can give a reason for why it's there.

**Comment by neonstalwart** [comment]
maybe the `mdRender` component name leads you to believe it contains vdom.  it's a component that renders markdown but `mdRender` produces state and `mdRenderRender` produces vdom - maybe that's the confusion?

**Comment by matthewp** [comment]
@neonstalwart You know what, I think I misread it. I though the textarea here was vdom: https://github.com/Raynos/mercury/blob/master/examples/markdown/component/inlineMdEditor.js#L35

but it's not. So it seems that `mercury.input` is a key piece to explain how encapsulation can work. So I'll read up on this module and learn what it's doing.

**Comment by neonstalwart** [comment]
yeah, i wrote the markdown example to specifically try and demonstrate encapsulation.  if there are patterns that can be improved in that example, i'd be glad to explore them.

**Comment by matthewp** [comment]
Yeah it's making more sense now. You are basically declaring events and functions they are bound to as part of your local state. And then you can then reuse them in render. Makes sense!

https://github.com/Raynos/mercury/blob/master/examples/markdown/component/textarea.js#L53

**Comment by Raynos** [comment]
@matthewp you should also be aware of how our "cursors" work.

A component can return a state object that is embedded in a larger state. it can then read / write to its own state. 

This gives the illusion of local state, however when you update your own state it triggers and update in the larger state which triggers a re-render.

You can see another example of it here:

 - https://github.com/Raynos/mercury/blob/master/examples/number-input/browser.js#L10-L14
 - https://github.com/Raynos/mercury/blob/master/examples/login-form/browser.js#L12

**Comment by matthewp** [comment]
Thanks @Raynos I was aware of that, I was just confused as to how a component has access to the local state. It seems that it's within the main exported module that creates the state, which is fine. So you set up your event-receiving functions there.

**Comment by alexmingoia** [comment]
You may be interested in my experimental implementation of such a component: https://github.com/alexmingoia/virtual-dom-component.

**Comment by matthewp** [comment]
Very interesting! I'll definitely play around with it. I can't tell, where is state actually defined? From the source the constructor is setting state to be an empty object, where would an extender define that components state values?
