### ISSUE TITLE
Support for ES6 tagged templates

### ISSUE THREAD

**Issue by tracker1** [Raynos/mercury#130]
This would be limited to updated environments or transpilers with support (6to5, etc).

see: http://updates.html5rocks.com/2015/01/ES6-Template-Strings#tagged-templates

example:

```js
var t = require('mercury').t; //t for template
App.render = function render(state) {
  return t`
    <div class="counter">
      The state <code>clickCount</code>
      has value: ${state.value}.
      <button ${t.click(hg.send(state.channels.clicks))}>Click me!</button>
    </div>
  `;
};
```

`t` would be a function that re-assembles the parts into rendered template... for the `ev-*` events, helper methods attached to t can be used... which can then render out... in this case `${t.click(...)}` would attach the click handler to the field...  I'm honestly not sure what level of overhead this would bring, or if it would be worth it... but it's an idea.

**Comment by alexmingoia** [comment]
Pretty cool. This belongs as a separate module that uses `virtual-dom/h`. There's no need for it to be in mercury.

This is just the beginning of a flood of DSL's for doing everything as a multiline string.... queries, templates, etc. ES6: God help us all.... :stuck_out_tongue_winking_eye:

**Comment by Raynos** [comment]
This would be a great thing to write as a module. `require('virtual-hyperscript-template')`

I encourage you to try this idea as a separate package and get a working prototype :)

I think this would be a really cool feature for people wanting to port applications from HTML to mercury. Although you can also use http://crowdecon.com/tools/htext_converter.php to convert HTML to hyperscript.

**Comment by tracker1** [comment]
@Raynos thinking on it, not quite sure how it would be best implemented... would probably have to track the inputs (that are an object/function), injecting a formatted string for placeholders, parse the result html into a virtual dom, then walk it replacing the appropriate properties with the js objects/function references... could work though.

**Comment by Raynos** [comment]
@tracker1 sounds about right, you need to cast the HTML into a vdom and then walk the vdom and populate all the placeholders.

**Comment by tracker1** [comment]
Note to self... https://github.com/unframework/html2hyperscript

may be able to modify this as a starting point...

**Comment by tracker1** [comment]
Created a [virtual-hyperscript-template project](https://github.com/tracker1/virtual-hyperscript-template) to work towards this functionality... leaving this open until that works, or someone else gets to it first... will close once implemented (so others can find a solution)...  though, the performance may very well be a serious issue in the conversion, so may not be at all practical.

**Comment by matthewp** [comment]
Very cool. Note that there is [a project](https://github.com/marcelklehr/vdom-virtualize) which will turn an html string into vdom tree.

**Comment by tracker1** [comment]
@matthewp thanks, that gets me halfway there...

thinking of replacing each field with `\036\037${i}\037\036` where i is the number representing the field in the collection... which should be a good replacement scheme... 036-036 being ascii 30-31 (record-unit separator)... the sequence should be easy enough to search for in the vdom tree values.

**Comment by kumavis** [comment]
awesome! please keep us posted on your progress :beers:
