### ISSUE TITLE
Weird escaping with 14.0.0

### ISSUE THREAD

**Issue by matthewp** [Raynos/mercury#131]
After upgrading to 14.0.0 (from 12.0.0) the app is no longer correctly stringified in Node and therefore you get stuff like this:

```html
<script>
window.__JSON_GLOBALS_[&#x22;state&#x22;] = {
    &#x22;foo&#x22;: &#x22;bar&#x22;
}
</script>
```

Notice that it's double quotes that are being converted to hex.  Not sure where the issue is, probably in virtual-dom although I can't find a commit that causes it.

**Comment by Raynos** [comment]
strange. the stringify code is not in virtual-dom, its in virtual-dom-stringify.

**Comment by matthewp** [comment]
The issue is that the tag names are capitalized and stringify doesn't check for this. Was there any changes in virtual-dom that caused this? It is a stringify issue so I'll submit the fix there, just curious as to when this broke.

**Comment by matthewp** [comment]
I think this is probably the breaking commit: https://github.com/Matt-Esch/virtual-dom/commit/e21dc39f1677382bd4a5a651a96ca9ebd51c5646

So it became an issue with 1.3.0.

**Comment by matthewp** [comment]
Created an issue there https://github.com/alexmingoia/virtual-dom-stringify/issues/19

**Comment by matthewp** [comment]
Ok, it's been merged: https://github.com/alexmingoia/virtual-dom-stringify/pull/20 Sorry for filing in the wrong repo, I thought it could be the virtual-hyperscript causing the encoding.
