### ISSUE TITLE
time-travel.js fille

### ISSUE THREAD

**Issue by kuraga** [Raynos/mercury#133]
We have `/time-travel.js` in the root.
Should it be `/examples/lib/time-travel.js`?

**Comment by kuraga** [comment]
Folks, in short: I really want to be a contributor of this project.

I found this (I hope) architecture for 18 month using JavaScript. And came to mind "server for API, client for UI" after 3 years of Ruby on Rails. I've said good bye, Angular month ago. Because it likes Rails: fat and non-modular. Well I should move on React because of "it's the next generation". Because of it come with strategy "components are isolated" though. But it's fat too! Unmodular! And I've found your project!

It comes with all we need: observers for model, manipulation of (V)DOM for view and events for controller. Nothing more needed that cannot be isolated and may be used separated! (Also router, maybe?) It's truly modular!!! It's excellent! Well I don't see it's truely tiny but modularness take me a chance to use some other (tiny) modules, no problems!

But there are some problems: no guide, no interconnects docs, no single develop model, no single quality control (this patch  is an example), no site and is there a plan? Ohh... And your versioning system is the worst in the world! :smile: 

And if I will use this framework in my project (I think I will) then I want to improve this framework. Well VDOM concept is new for me and I can't be a prof here. But I can come it.

The next step I want to do - to see a plan. Okay TODO. The whole TODO. Where do you want to see it? Github issues? Google docs?

Let's start with new power! The future is waiting for us!

**Comment by kuraga** [comment]
Folks, in short: I really want to be a contributor of this project.

I found this (I hope) architecture for 18 month using JavaScript. And came to mind "server for API, client for UI" after 3 years of Ruby on Rails. I've said good bye, Angular month ago. Because it likes Rails: fat and non-modular. Well I should move on React because of "it's the next generation". Because of it come with strategy "components are isolated" though. But it's fat too! Unmodular! And I've found your project!

It comes with all we need: observers for model, manipulation of (V)DOM for view and events for controller. Nothing more needed that cannot be isolated and may be used separated! (Also router, maybe?) It's truly modular!!! It's excellent! Well I don't see it's truely tiny but modularness take me a chance to use some other (tiny) modules, no problems!

But there are some problems: no guide, no interconnects docs, no single develop model, no single quality control (this patch  is an example), no site and is there a plan? Ohh... And your versioning system is the worst in the world! :smile: 

And if I will use this framework in my project (I think I will) then I want to improve this framework. Well VDOM concept is new for me and I can't be a prof here. But I can come it.

The next step I want to do - to see a plan. Okay TODO. The whole TODO. Where do you want to see it? Github issues? Google docs?

Let's start with new power! The future is waiting for us! :smiley: 

/cc @Raynos @kumavis @neonstalwart

**Comment by Raynos** [comment]
@kuraga you are now a collaborator :) You have commit access.

Make sure to checkout https://github.com/Raynos/mercury/blob/master/CONTRIBUTION.md for guidelines on contributions.

**Comment by Raynos** [comment]
time-travel.js is a module in the root because i want people to be able to import `require('mercury/time-travel')` in their applications.

The files in `examples/lib/*` are just internal helpers for the examples that are not part of mercury.

**Comment by Raynos** [comment]
We have a router btw, https://github.com/twilson63/mercury-router

**Comment by Raynos** [comment]
> But there are some problems: no guide, no interconnects docs, no single develop model, no single quality control (this patch is an example), no site and is there a plan? Ohh... And your versioning system is the worst in the world! :smile:

Documentation is indeed lacking, there are no API docs. There are a bunch of guides in the `docs/` folder though. I started documenting the API of the individual modules (since most of mercury is just re-exporting).

There is no site yet, nor is there a plan for one. Might be nice to have one.

The versioning scheme is actually brilliant, we follow semver to the letter.

**Comment by Raynos** [comment]
> The next step I want to do - to see a plan. Okay TODO. The whole TODO. Where do you want to see it? Github issues? Google docs?

If you want to contribute a plan, contribute to issues :)

**Comment by Raynos** [comment]
I added a ROADMAP a long time ago ( https://github.com/Raynos/mercury/blob/master/ROADMAP.md ) to help me keep track, but it's rather stale now.

**Comment by kuraga** [comment]
Just an opinion that `14.0.0` version is a `0.14.0` indeed :smile: Well it's a semi-joke. But `0.14.0` is a semver too.

Thanks for answers!

**Comment by neonstalwart** [comment]
@kuraga i partially agree with your for the version number, it was probably a mistake to ever declare 1.x for mercury and the maturity of the project is definitely closer to what you would typically see at 0.14.x rather than 14.x. with semver though, once 1.x is tagged then to continue to follow semver you can quickly end up at 14.x instead of 0.14.x if you happen to tag 1.x too early.  that said, i support continuing to strictly follow semver.

**Comment by Raynos** [comment]
You also have to remember that the reason we have 14.x is because I re-export 12 modules.

So If the 12 modules I re-export are all at v2 then mercury is at v13.

**Comment by Raynos** [comment]
This is just how it works for wrapper modules and generally why semver doesn't work as nicely for libraries with a large user interface.

**Comment by Raynos** [comment]
This is also why I recommend people copy `index.js` into their app and depend on everything directly.

**Comment by neonstalwart** [comment]
sure, but if we had not released 1.x then we could be 0.14.x rather than 14.x.  ultimately, i don't care about the number and i'm glad we follow semver strictly - that's the thing which matters most going forward.
