### ISSUE TITLE
Exception when initializing an app on an element with the same tag name

### ISSUE THREAD

**Issue by matthewp** [Raynos/mercury#136]
This happened when I upgraded from 12.0 to 14.0.

My code is basically the same as shown here: https://github.com/Raynos/mercury/blob/master/examples/server-rendering/browser.js#L28

If `targetElem` has the same tagName as the element returns by render you get the exception:

```
Uncaught SyntaxError: Failed to set the 'contentEditable' property on 'HTMLElement': The value provided ('') is not one of 'true', 'false', 'plaintext-only', or 'inherit'.
```

The error occurs here: https://github.com/Matt-Esch/virtual-dom/blob/master/vdom/apply-properties.js#L43

It attempts to set node['contentEditable'] = '' which I guess is invalid so the browser throws.

Not sure what caused this error to happen. I'm not using contenteditable, that must be the default value in the browser and virtual-dom is mistakenly diffing it. What is the proper fix for this? Should I file in virtual-dom?

**Comment by kumavis** [comment]
hmm im not sure -- try the `hg.app(document.body, app, render, opts)` signature?

**Comment by matthewp** [comment]
Same result.

**Comment by kumavis** [comment]
if you leave out `initialTree` https://github.com/Raynos/mercury/blob/master/examples/server-rendering/browser.js#L32 does it work?
if so maybe `vdom-virtualize` needs to be in sync with `mercury/node_modules/vdom`

**Comment by Raynos** [comment]
This is probably a bug in vdom-virtualize. There was an issue about `contentEditable` on virtual-dom as well.

**Comment by Raynos** [comment]
https://github.com/Matt-Esch/virtual-dom/issues/176

**Comment by Raynos** [comment]
Actually this is a bug in virtual-dom.

**Comment by matthewp** [comment]
Great, will track there then, thanks.
