### ISSUE TITLE
observ-* and Object.observe

### ISSUE THREAD

**Issue by kuraga** [Raynos/mercury#144]
Hey folks,

can we replace `observ-*` dependencies with a `Object.observe` technique in the future?

What's your thoughts?

**Comment by Raynos** [comment]
No. 

`Object.observe` allows you to observe changes, however that requires you to mutate your state object. If you read the `observ-*` source code, you find that all mutation methods actually make shallow copies.

The ability to "observe" state is less important then the ability to keep the state immutable.

**Comment by kuraga** [comment]
Thanks.

**Comment by kuraga** [comment]
@Raynos a question about immutability. Where does immutability end and does mutability start?

Facts:
1a) [we set new `value` property](https://github.com/Raynos/mercury/blob/master/examples/count.js#L17)
1b) and then [get **new** `state`](https://github.com/Raynos/mercury/blob/master/examples/count.js#L16) via **event** (channel), i.e. **not from** previous `render`;
2) [leaves are mutable](http://requirebin.com/?gist=97855bc25be155afe666).

So, do we store current `state`? Where? So, do we *change* it? Do we *mutate* it? Or do we mutate `state` reference but not the `state` object, do you mean?
Then is state really immutable? Where does immutability end and does mutability start?

**Comment by kuraga** [comment]
@kumavis @neonstalwart @Raynos a question about immutability. Where does immutability end and does mutability start?

Facts:
1a) [we set new `value` property](https://github.com/Raynos/mercury/blob/master/examples/count.js#L17)
1b) and then [get **new** `state`](https://github.com/Raynos/mercury/blob/master/examples/count.js#L16) via **event** (channel), i.e. **not from** previous `render`;
2) [leaves are mutable](http://requirebin.com/?gist=97855bc25be155afe666).

So, do we store current `state`? Where? So, do we *change* it? Do we *mutate* it? Or do we mutate `state` reference but not the `state` object, do you mean?
Then is state really immutable? Where does immutability end and does mutability start?

**Comment by kristianmandrup** [comment]
You don't want to mutate EVER (IMO)! See clojure, datomic etc. Mutable programs were mostly "invented" for ease of use and limited memory back in the day... a mutable app doesn't scale, causing too many problems as it grows...

https://thechangelog.com/rich-hickeys-greatest-hits/
http://www.datomic.com/videos.html
https://vimeo.com/97408202

We are finally rethinking our whole approach to computing, leveraging our much improved infrastructure
