### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by kuraga** [Raynos/mercury#146]
We have build error. `zuul`'s iPhone fails. Do you know what's the problem?

And does `testling` (which doesn't test at all, config is broken) duplicate `zuul`?

**Comment by kuraga** [comment]
And does `testling` (which doesn't test at all, config is broken) duplicate `zuul`?

**Comment by Raynos** [comment]
testling is deprecated and can be removed in favor of zuul.

I do not know what to do about zuuls iphone failures.

Looks like iphone timed out, lets trigger another build.

**Comment by kuraga** [comment]
Seems like it's not an iPhone problem.

Something like SauceLabs' limits maybe?

**Comment by kuraga** [comment]
ping

**Comment by Raynos** [comment]
I turned iphone off. Lets edit the zuul config and turn all the stuff off.

**Comment by kuraga** [comment]
Hm. Passed. Very strange.

When we turned off iPhone then iPad failed. But iPad didn't fail before this. Now everything's ok.

I will try to turn on iPhone, Android and iPad later by myself. Thanks.
