### ISSUE TITLE
Travis doesn't handle pull requests

### ISSUE THREAD

**Issue by kuraga** [Raynos/mercury#147]
Travis doesn't handle pull requests.

Are hooks enabled?

**Comment by Raynos** [comment]
Looks like i configured everything. Dont know why travis doesnt show pull requests, but its testing branches.

**Comment by neonstalwart** [comment]
@Raynos travis is only testing pushes.  for some reason it's not doing pull requests.  https://travis-ci.org/Raynos/mercury/settings shows that travis is configured for pull requests is there a way to check github to make sure travis can see the pull requests?

**Comment by kuraga** [comment]
I think we have to lookup in git or Github's (reposiory's hooks') settings

**Comment by kumavis** [comment]
I dont have access to settings for this repo, so i cant confirm hooks

**Comment by kuraga** [comment]
Feel free to reopen
