### ISSUE TITLE
Mercury and shouldComponentUpdate

### ISSUE THREAD

**Issue by rawberg** [Raynos/mercury#150]
I'm new to React and Immutable data structures in JS. I've been looking into Mercury along with Morearty and Omniscient.

How does Mercury decide to attempt to re-render the view? Is it just based on change events from observ-struct? Is there a concept of avoiding the vdom diff calculations if the data hasn't actually changed?

[Omniscient](https://github.com/omniscientjs/omniscient/blob/master/shouldupdate.js#L71) and [Moreatry](https://github.com/moreartyjs/moreartyjs/blob/master/src/Morearty.js#L537) both override shouldComponentUpdate. Does Mercury need or already have a similar pattern?

**Comment by Raynos** [comment]
Mercury had mercury.partial which uses vdom thunks.

**Comment by rawberg** [comment]
Thanks for the speedy response. [Thunks page](https://github.com/Raynos/mercury/blob/master/docs/thunks.md) in the docs explains it greater detail!
