### ISSUE TITLE
Issue inside the serverside example

### ISSUE THREAD

**Issue by martintietz** [Raynos/mercury#159]
The serverside rendering itself is working fine. But there is a problem on the client when the app is started (https://github.com/Raynos/mercury/blob/master/examples/server-rendering/browser.js#L30):
```js
hg.app(null, app, App.render, {
    initialTree: prevTree,
    target: targetElem
});
```
This code does not seem to work with the current version of mercury as hg.app looks like the following (https://github.com/Raynos/mercury/blob/master/index.js#L109):
```js
function app(elem, observ, render, opts) {
    if (!elem) {
        throw new Error(
            'Element does not exist. ' +
            'Mercury cannot be initialized.');
    }

    mercury.Delegator(opts);
    var loop = mercury.main(observ(), render, extend({
        diff: mercury.diff,
        create: mercury.create,
        patch: mercury.patch
    }, opts));

    elem.appendChild(loop.target);

    return observ(loop.update);
}
```
The problem in this example is that elem is ```null``` and an error is thrown.

**Comment by martintietz** [comment]
To answer my own question: simply removing any usage of ```elem``` from inside the app function solves the issue. It would be nice if this could be stated inside the example.

**Comment by danielnaab** [comment]
@martintietz you can pass document.body into app() if you don't have a dom node.
