### ISSUE TITLE
Routing?

### ISSUE THREAD

**Issue by kokujin** [Raynos/mercury#162]
Forgive my ignorance. How can routing be handled with Mercury? Can one consider "States" to correspond to routes?

**Comment by alexmingoia** [comment]
At the simplest level... you have a "path" property in your state and you have a switch statement in a render method to show different views:

```javascript
function render(state) {
  switch (state.urlPath) {
    case '/':
      return <HomeView />
    case '/users':
      return <UsersView />
}
```

For route parameters and history API there is [mercury-router](https://github.com/twilson63/mercury-router).

**Comment by kokujin** [comment]
Thanks
