### ISSUE TITLE
Gitter?

### ISSUE THREAD

**Issue by aknuds1** [Raynos/mercury#165]
Would you mind creating a [Gitter](https://gitter.im/) room for discussing Mercury? Would be very useful for someone trying to learn Mercury.

**Comment by twilson63** [comment]
@aknuds1 it is already setup : https://gitter.im/Raynos/mercury

**Comment by aknuds1** [comment]
@twilson63 Would you mind adding a Gitter badge to the README, so that people are aware?

**Comment by kumavis** [comment]
@aknuds1 we accept PRs, this is open source after all

added one here https://github.com/Raynos/mercury/pull/167
