### ISSUE TITLE
Canonical way to update state from an Ajax call?

### ISSUE THREAD

**Issue by aknuds1** [Raynos/mercury#166]
What's the canonical way to update state when an Ajax call, that was *not* triggered by the user, returns?

**Comment by neonstalwart** [comment]
@aknuds1 it probably depends on how the response affects state.

here's an example using promises where the call gets the preferences for the currently logged in user
```js
var state = App();

// ...

getPreferences(user).then(function (preferences) {
  state.preferences.set(preferences);
});
```

anything observing `state.preferences` will be updated and the app will be rendered again.

do you have something more specific that you're not sure about?

**Comment by aknuds1** [comment]
@neonstalwart I started out trying to do that directly (i.e. change state variables when the Ajax call returns), but I experienced that it didn't trigger a re-render.

What worked instead was to make the Ajax return trigger an event, for which a listener updated application state. *This* triggered a re-render.

```
// Snippet
hg = require('mercury);
let dataLoadedEvent = hg.input();
dataLoadedEvent((value) => {
    // Update state
  });
loadData.then(dataLoadedEvent);
```

**Comment by neonstalwart** [comment]
if what i showed you didn't work then you have a problem with how you've put your `state` together.  do you have a small example that demonstrates how it doesn't work?  you can leave out the ajax call and just manually change the value for the sake of demonstration.

events can be useful but in this case i think updating `state` directly is a more direct option.

**Comment by aknuds1** [comment]
@neonstalwart Nevermind, I made it work after removing the event indirection. No idea why it wouldn't work before.
