### ISSUE TITLE
Reflect changes in value on shared state.

### ISSUE THREAD

**Issue by hemanth** [Raynos/mercury#173]
For example on [shared-state](http://raynos.github.io/mercury/examples/shared-state.html) if we do:

```js
document.querySelector('input').value = 'meow'
```
`p.content` does not get updated.

//cc @Raynos @ashnur

**Comment by ashnur** [comment]
I think that would go against unidirectionality.

**Comment by hemanth** [comment]
document.querySelector('input').value vs the user typing in the input area?

**Comment by neonstalwart** [comment]
@hemanth the problem is that setting the value directly does not generate a DOM event - this is not something which mercury can fix :smile: 

see http://output.jsbin.com/yewiwohome/1/edit?html,console,output

**Comment by hemanth** [comment]
:+1: @ashur was describing the same at #javascript :)
