### ISSUE TITLE
Using vdom-to-html doesn't work (returns empty string)

### ISSUE THREAD

**Issue by DominicTobias** [Raynos/mercury#192]
Hi, using node v4.2.1 and vdom-to-html with mercury doesn't work.

Don't know if this is related but I noticed that:
require('virtual-dom/vnode/vnode'); // works
require('vtree/vnode'); // doesn't work

For example:

```
var toHTML = require('vdom-to-html');
var h = require('mercury').h;
toHTML(h('p', 'Hello')); // Returns nothing
```

Am I missing something obvious? Thanks

**Comment by danielnaab** [comment]
@DominicTobias: vdom-to-html uses [virtual-dom 2.0.0](https://github.com/nthtran/vdom-to-html/blob/master/package.json#L12) while Mercury depends on [1.3.0](https://github.com/Raynos/mercury/blob/master/package.json#L48), and v2 has breaking changes. You can make your own local mercury.js with dependencies on ^2.0.0, or just import the virtual-dom dependencies directly. Either way, you'll want to depend on just one version, so your build artifact doesn't duplicate code.

**Comment by DominicTobias** [comment]
Thanks I'll just use 1.2.5 @ vdom-to-html

**Comment by gcallaghan** [comment]
Is there any plan to move Mercury to virtual-dom 2.x ?

**Comment by tommymessbauer** [comment]
If there is a list of things that need to be done to upgrayedd mercury, I'll be happy to chip in and knock some of them out.  

Please let me know how I can help.

**Comment by eightyeight** [comment]
Same here, I'd be happy to take on some work related to this.

**Comment by DeepAnchor** [comment]
I'd love to see this project advance, especially in regards to some of the points mentioned in the [standing challenges](https://github.com/Raynos/mercury/issues/140) thread  -the most crucial of which I think is the having a formal component interface for people to design reusable components around.
