### ISSUE TITLE
syntax of h

### ISSUE THREAD

**Issue by cauburtin** [Raynos/mercury#199]
Hi, what are your sights on the syntax:

    h('html', [
      h('head', [
        h('title', 'Server side rendering')
        ]),
      h('body', [
        content,
        h('script', JSONGlobals({
          state: state
        })),
        h('script', {
          src: 'bundle.js'
        })
        ])
      ]);

    // vs

    h('html').add(
      h('head').add(
        h('title').text('Server side rendering')
      ),
      h('body').add(
        content,
        h('script').add(JSONGlobals({
          state: state
        })),
        h('script').attr({
          src: 'bundle.js'
        })
      )
    );

personally I prefer the second, even if slightly more verbose it's a bit more clear, .text is a shortcut for .attr({text..: ..})

    var tree = h('div.foo#some-id', [
        h('span', 'some text'),
        h('input', { type: 'text', value: 'foo' })
    ]);

would be 

    var tree = h('div.foo#some-id').add(
        h('span').text('some text'),
        h('input').attr({ type: 'text', value: 'foo' })
    );

@Raynos  (sorry to ping you:), would appreciate your input)

**Comment by gcallaghan** [comment]
Isn't this really more of a [hyperscript](https://github.com/Matt-Esch/virtual-dom) question?

**Comment by cauburtin** [comment]
sorry I realized it too, will move it there, thanks
