### ISSUE TITLE
What is the right way to pass data to click event handlers?

### ISSUE THREAD

**Issue by laduke** [Raynos/mercury#214]
Sorry. I've been looking around for a while, and can't figure this out. I have a list of links with unique IDs or whatever. When I click one, it want to pass some info along -which button got clicked. 

With an input field, you can use `name: 'foo'` to populate the 2nd parameter (commonly called 'data' in the examples) with data.foo... 

this works but might be the wrong thing to do:

`'ev-click': hg.send(channels.selectUser, user_name)`

thank you

**Comment by gcallaghan** [comment]
That looks right to me.
