### ISSUE TITLE
server-side-rendering

### ISSUE THREAD

**Issue by RnbWd** [Raynos/mercury#55]
I noticed mercury.app appends html to the target element, while react completely replaces everything in the target element. If I pre-render the html server-side, react knows what to replace because every element has a 'react-id'. Trying to replicate that functionality I changed mercury.app so that it erases the target element before rendering.

````
function app(elem, observ, render, opts) {
    mercury.Delegator(opts);
    var loop = mercury.main(observ(), render, opts);
    elem.innerHTML = '';
    elem.appendChild(loop.target);
    return observ(loop.update);
}
````

I'm not sure if this is the best way? With React, I noticed that sending pre-rendered html made the sites load instantaneously, instead waiting up to a few seconds for the React library to load and render the page. I load the libraries async - the user doesn't even realize what's happening. I'm testing with mercury by async loading via scriptjs after x seconds, and it looks good thus far. I'm not sure how it'll look with the bigger examples. I was just wondering if something like this was planned in the design? It's modular enough to implement this pretty easily. I'm not sure how to render the h server-side properly thou, I'm just creating html and replacing it at the moment.

**Comment by cauburtin** [comment]
> It's still a work in progress.
is it ready now? I've seen [this](https://github.com/Matt-Esch/virtual-dom/issues/50#issuecomment-50102165) for example

**Comment by Raynos** [comment]
@cauburtin server-side rendering kind of works.

It's definitely possible, it needs a little bit of boilerplate in your app, you can see the example

**Comment by cauburtin** [comment]
ok thanks, I'm going to deal with isomorphic code (necessary in that case -SEO)). I guess the difficulty is for events inside that tree? A tree without event handlers inside doesn't seem hard to stringify
