### ISSUE TITLE
outline strategy for CI

### ISSUE THREAD

**Issue by neonstalwart** [Raynos/mercury#62]
@Raynos in https://github.com/Matt-Esch/virtual-dom/pull/90#issuecomment-48853544 you mentioned that testing mercury is a manual process currently.  this MUST become automated.

i may be able to contribute towards this effort but in order to get contributions to help move towards the goal of CI, what is your plan for automated testing?  what tools and technology do you plan on using to have tests running in browsers?  even if there are currently no tests, put the mechanism in place to run tests in supported browsers so that all that's left is for tests to be written.

NOTE: anything short of running tests in browsers is not sufficient - i.e. phantomjs, min-document, jsdom, etc are not enough.

**Comment by kumavis** [comment]
other than the fact that we need more tests, i think this is good to close
