### ISSUE TITLE
The great 0.0.13 virtual-dom upgrade

### ISSUE THREAD

**Issue by Raynos** [Raynos/mercury#63]
This is an issue for blockers on the upgrade

 - [x] @raynos write a test in mercury for `examples/bmi-counter.js`
 - [x] @raynos upgrade virtual-hyperscript to 0.0.13 + author tests for virtual-hyperscript
 - [x]  @Matt-Esch upgrade main-loop to 0.0.13 + author tests for main-loop
 - [x] @raynos add getElementsByClassName to min-document
 - [x] @Matt-Esch upgrade mercury to 0.0.13
 - [x] @Matt-Esch upgrade vdom-thunk, virtual-hyperscript, main-loop in mercury
 - [x] manually test all examples
 - [x] rebase the branches on master + test those examples
 - [x] #shipit

**Comment by kumavis** [comment]
This has completed, issue can be closed.

**Comment by Raynos** [comment]
Cool :)

**Comment by Raynos** [comment]
@kumavis I added you as a collaborator :)
