### ISSUE TITLE
Update observ-array dependency

### ISSUE THREAD

**Issue by afandria** [Raynos/mercury#81]
The observ-array package is at release v2.0.0, and notably includes transactions, which are very helpful for batching together diffs on mercury arrays. Could this project's package.json file be updated to that version number?

**Comment by joshgillies** [comment]
This was issue should have been closed with https://github.com/Raynos/mercury/commit/6f1af5233841e64ed5aae19b544b314539f6959c yeah?

**Comment by afandria** [comment]
Yup, thanks.
