### ISSUE TITLE
How does this compare to mithril?

### ISSUE THREAD

**Issue by fyyyyy** [Raynos/mercury#95]
Could you provide a simple code comparison spreadsheet towards other Vdom frameworks ?
That would be really helpful in keeping an overview where mercury fits best, at a glance.

e.g. module
in React: instance of bla
in Mithril: plain JS function
in Mercury: ...

Cheers

**Comment by sdegutis** [comment]
Seconded. How is this better than Mithril? It may very well be, I just don't see how. A comparison or explanation in the readme would help.

**Comment by Raynos** [comment]
There have been talks on the ideas behind mercury.

The main differences are:

 - Mithril is one file, mercury is many small modules.
 - Mercury encourages immutability and FRP.
 - Mithril takes an MVC approach
 - Mithril ships with a default router, mercury has a standalone mercury-router module.

Mithril feels very imperative MVC to me, where as mercury encourages FRP & unidirectional approaches.

**Comment by tommymessbauer** [comment]
Adding my 2 cents (though by the length, it might be a couple dollars).  I hope this helps.  I reviewed React, Mithrill, and Mercury.

*Disclosure* - I have not built anything large with React or Mithril (and currently in development on a big thing with Mercury).  I just reviewed them and decided to use Mercury.

I chose Mercury for 3 reasons. 

* **Unidirectional**

Simplifying rendering to this type of flow makes life much much easier.  Everything acts on model, then flows downstream.  Without diff/patch, this flow would not perform well.  But you already knew that and that is why you are looking at reactive rendering.

**model -> f(x) -> vdom -> diff/path -> dom**

Having re-entrant flows, views, etc in HTML can get really ugly.  For example, Backbone can quickly deteriorate to a mess if you don't think about the flow from history (address bar) to parent view to child view to peer view to model and back to address.  (no offense to Backbone, this is an error that developers make.  Backbone just does not care)

* **Modularity**.  

Routing is a solved problem and you probably already have one you like (I did).  I also already had api clients for the browser so I didn't need an xhr wrapper.  Taking a framework that tries to do too much (xhr, routing, etc) when you really want rendering and observing is not ideal.  

You can replace everything if you want.  Don't like the dom-delegator, observable lib, etc?  Then you can replace them (we probably need a cookbook for that).  I found things work well OOTB.  I just hooked up my router and api client and things are great.

* **The code is readable and straight forward.** 

I may be re-stating modularity here, but this is important.  We all hit a point where our code is not doing what we expect.  IMHO, one should not under-estimate the value of being able to break out a component, write a test without the "framework," and find the conflict.  

**Mithril** - Looks like a promising "framework" (disclosure - I am in the libs > frameworks camp).  It felt like it had too many extra things in it for my taste and we would have needed to either migrate our routing and controllers to Mithrill or make some sort of adapter.  The community is not as large as React to overcome the issues.

**React** - Really large library (on disk) and it was not obvious to me how to de-couple things.  I have friends that use it and are happy with it, but it looked like a lot of refactoring, tooling, and compiling chains to get it into our solution.  I like that React is only trying to solve rendering.  Seems like many people use it with JSX & Flux which might drag in more dependencies.  There seems to be a large community around React.

People are making great things with all 3 so ultimately, this comes down to what matters to you.  Google search and you will find a things.

**Comment by sdegutis** [comment]
@tommymessbauer This is an excellent description and comparison, and it matches what I know so far about the alternatives, which gives it extra credibility. I think it would be great if this goes into Mercury's readme.

**Comment by Raynos** [comment]
@tommymessbauer 

Let's add the comparison prose; Right above the Mercury vs React in the README, open a PR :)
